version: '3.8'

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: userdb       # Nome do usuário do banco de dados
      POSTGRES_PASSWORD: 1234     # Senha do usuário
      POSTGRES_DB: centraldb     # Nome do banco de dados
    ports:
      - "5432:5432"              # Mapeamento da porta 5432 para o host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistência dos dados do banco
    networks:
      - app-network

  # Serviço Backend
  backend:
    build:
      context: ./central-vagas-backend  # Caminho para o código do backend
    container_name: backend-container
    environment:
      DB_HOST: postgres         # Nome do serviço do PostgreSQL (deve ser o mesmo do Docker Compose)
      DB_USER: userdb           # Nome do usuário do banco de dados (deve ser o mesmo do PostgreSQL)
      DB_PASSWORD: 1234         # Senha do banco de dados (deve ser a mesma do PostgreSQL)
      DB_DATABASE: centraldb    # Nome do banco de dados (deve ser o mesmo do PostgreSQL)
      DB_PORT: 5432             # Porta de conexão do PostgreSQL
    ports:
      - "3000:3000"  
      - "80:80"           # Mapeamento da porta 3000 para o host
    depends_on:
      - postgres                # Garante que o PostgreSQL seja iniciado antes do backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge              # Rede bridge para os contêineres se comunicarem

volumes:
  postgres-data:
    driver: local               # Volume persistente para os dados do PostgreSQL
